import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffe0b2",
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },

  card: {
    backgroundColor: "#ffffff",
    padding: 40,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 25,
    elevation: 5,
    width: "90%",
    alignItems: "center",
  },
  title: {
    fontSize: 48,
    fontWeight: "800",
    color: "#ff7043",
    textShadowColor: "#ffd180",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    marginBottom: 30,
  },
  textarea: {
    width: "100%",
    height: 200,
    padding: 20,
    marginBottom: 25,
    fontSize: 18,
    borderWidth: 3,
    borderColor: "#ffa726",
    borderStyle: "dashed",
    borderRadius: 20,
    backgroundColor: "#fff9f0",
    textAlignVertical: "top",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  analyzeButton: {
    backgroundColor: "#66bb6a",
    paddingVertical: 16,
    paddingHorizontal: 30,
    borderRadius: 50,
    marginBottom: 30,
    shadowColor: "#66bb6a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 5,
  },
  analyzeButtonText: {
    color: "white",
    fontSize: 22,
    fontWeight: "700",
  },
  moodResult: {
    alignItems: "center",
    marginBottom: 40,
  },
  emoji: {
    fontSize: 70,
    marginBottom: 15,
  },
  moodText: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#5d4037",
    marginTop: 10,
  },
  confidenceText: {
    fontSize: 22,
    color: "#6d4c41",
    marginTop: 8,
  },
  backButton: {
    backgroundColor: "#fb8c00",
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 50,
    shadowColor: "#fb8c00",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 5,
  },
  backButtonText: {
    color: "black",
    fontSize: 20,
    fontWeight: "700",
  },
});
